[app]
title = MyTVPlayer
package.name = mytvplayer
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf
source.exclude_exts = spec
source.exclude_dirs = tests, bin
source.include_patterns = assets/*
version = 0.1
requirements = python3,kivy==2.2.1,pillow,pyjnius,android,urllib3,ssl
orientation = portrait
fullscreen = 0
android.api = 33
android.ndk = 25b
android.ndk_path = 
android.sdk_path = 
android.add_assets = msyh.ttf
android.add_asset_dir = assets
android.permissions = INTERNET,ACCESS_NETWORK_STATE
android.arch = arm64-v8a,armeabi-v7a
android.build_type = debug
android.clean = True
android.ndk_api = 21
android.p4a_branch = master
android.enable_androidx = True
android.enable_multidex = True
android.use_aapt2 = True
android.target_sdk = 33
android.min_sdk = 21
android.dex_optimize = True
android.build_tool = 33.0.0
android.build_tools_version = 33.0.0
android.ndk_version = 25.2.9519653
android.sdk_platform = android-33
android.sdk_tools = 9477386
android.accept_sdk_license = True
android.logcat_filters = *:S python:D
android.presplash_color = #FFFFFF
android.window_softinput_mode = adjustResize
android.bundle = False
android.icon = 
android.launcher_icon = 
android.keystore = 
android.keyalias = 
android.keystore_pass = 
android.keyalias_pass = 
android.signed = False
android.build_dir = bin
